"""Presentation metadata for the managed Linux gateway environment."""

from __future__ import annotations

from typing import Any

from rns_meshtastic.gateway_config import MANAGED_FIELDS, POLICY_PROFILES, is_secret

GROUPS = (
    ("radio", "Meshtastic radio"),
    ("reticulum", "Reticulum topology"),
    ("safety", "LoRa safety"),
    ("public", "Public and private boundary upstreams"),
    ("discovery", "Discovery"),
    ("ifac", "IFAC protection"),
    ("lan", "LAN and Console"),
    ("lxmd", "LXMD mailbox"),
)


def _field(
    name: str,
    group: str,
    help_text: str,
    *,
    default: str = "",
    recommended: str | None = None,
    kind: str = "text",
    choices: tuple[str, ...] = (),
    minimum: float | None = None,
    maximum: float | None = None,
    advanced: bool = False,
    required: str | None = None,
    applies_when: tuple[tuple[str, tuple[str, ...]], ...] = (),
) -> dict[str, Any]:
    return {
        "name": name,
        "group": group,
        "help": help_text,
        "default": default,
        "recommended": recommended if recommended is not None else default,
        "type": kind,
        "choices": list(choices),
        "minimum": minimum,
        "maximum": maximum,
        "advanced": advanced,
        "secret": is_secret(name),
        "required_when": required,
        "applies_when": [
            {"field": dependency, "values": list(values)} for dependency, values in applies_when
        ],
    }


FIELDS = (
    _field(
        "MESHTASTIC_TCP_HOST",
        "radio",
        "IP address or DNS name of the dedicated Meshtastic TCP radio.",
        required="always",
    ),
    _field(
        "MESHTASTIC_TCP_PORT",
        "radio",
        "Meshtastic PhoneAPI TCP port.",
        default="4403",
        kind="integer",
        minimum=1,
        maximum=65535,
        advanced=True,
    ),
    _field(
        "MESHTASTIC_CHANNEL_INDEX",
        "radio",
        "Local channel slot used for channel broadcasts; PKI unicast remains Node-ID based.",
        default="0",
        kind="integer",
        minimum=0,
        maximum=7,
    ),
    _field(
        "MESHTASTIC_HOP_LIMIT",
        "radio",
        "Maximum Meshtastic LoRa hops. Three is appropriate for the shared mesh.",
        default="3",
        kind="integer",
        minimum=0,
        maximum=7,
    ),
    _field(
        "MESHTASTIC_MQTT_FORWARDING_POLICY",
        "radio",
        "inherit follows the radio OK-to-MQTT policy; force_off keeps bridge packets off MQTT.",
        default="inherit",
        choices=("inherit", "force_off"),
    ),
    _field(
        "RNS_MESH_MODE",
        "reticulum",
        "auto_multi_peer learns RNS destinations per Meshtastic peer; "
        "fixed unicast and broadcast remain available.",
        default="gateway_unicast",
        recommended="auto_multi_peer",
        choices=("auto_multi_peer", "gateway_unicast", "broadcast"),
    ),
    _field(
        "RNS_GATEWAY_ROLE",
        "reticulum",
        "Linux is normally the hub; broadcast requires client.",
        default="hub",
        choices=("hub", "client"),
    ),
    _field(
        "RNS_GATEWAY_NODE",
        "reticulum",
        "Remote Node ID for a gateway_unicast client.",
        required="RNS_MESH_MODE=gateway_unicast and RNS_GATEWAY_ROLE=client",
        applies_when=(
            ("RNS_MESH_MODE", ("gateway_unicast",)),
            ("RNS_GATEWAY_ROLE", ("client",)),
        ),
    ),
    _field(
        "RNS_ALLOWED_NODES",
        "reticulum",
        "Optional comma-separated Meshtastic Node-ID ingress allowlist; required by a fixed unicast hub.",
        applies_when=(
            ("RNS_MESH_MODE", ("gateway_unicast", "auto_multi_peer")),
            ("RNS_GATEWAY_ROLE", ("hub",)),
        ),
    ),
    _field(
        "RNS_MAX_PEERS",
        "reticulum",
        "Maximum learned Meshtastic peer interfaces.",
        default="32",
        kind="integer",
        minimum=1,
        maximum=512,
        advanced=True,
        applies_when=(
            ("RNS_MESH_MODE", ("gateway_unicast", "auto_multi_peer")),
            ("RNS_GATEWAY_ROLE", ("hub",)),
        ),
    ),
    _field(
        "RNS_PEER_ANNOUNCE_IDLE_SECONDS",
        "safety",
        "After this many seconds without inbound bridge traffic, suppress only ordinary "
        "periodic RNS announces to that peer. Data, proofs and path responses remain enabled; "
        "zero disables the safeguard.",
        default="900",
        kind="integer",
        minimum=0,
        maximum=86400,
        advanced=True,
        applies_when=(
            ("RNS_MESH_MODE", ("gateway_unicast", "auto_multi_peer")),
            ("RNS_GATEWAY_ROLE", ("hub",)),
        ),
    ),
    _field(
        "RNS_LORA_POLICY",
        "safety",
        "conservative protects shared RF; balanced is for a controlled private mesh.",
        default="conservative",
        choices=("conservative", "balanced", "custom"),
    ),
    _field(
        "RNS_RADIO_TX_INTERVAL",
        "safety",
        "Minimum seconds between Meshtastic transmissions. Policy profiles supply this value.",
        default="2.0",
        kind="number",
        minimum=0.25,
        maximum=60,
        advanced=True,
    ),
    _field(
        "RNS_RADIO_QUEUE_FRAGMENTS",
        "safety",
        "Bounded complete-frame admission queue in fragments.",
        default="32",
        kind="integer",
        minimum=4,
        maximum=1024,
        advanced=True,
    ),
    _field(
        "RNS_REPAIR_REQUEST_BUDGET",
        "safety",
        "Maximum missing-fragment requests in the rolling repair window.",
        default="12",
        kind="integer",
        minimum=1,
        maximum=120,
        advanced=True,
    ),
    _field(
        "RNS_REPAIR_BUDGET_WINDOW",
        "safety",
        "Repair budget rolling window in seconds.",
        default="60",
        kind="number",
        minimum=10,
        maximum=3600,
        advanced=True,
    ),
    _field(
        "RNS_PUBLIC_UPSTREAMS",
        "public",
        "Public host:port boundary interfaces. Public announces are never exported to LoRa.",
        kind="endpoint-list",
    ),
    _field(
        "RNS_PUBLIC_BOOTSTRAP_UPSTREAMS",
        "public",
        "Tick configured public boundary endpoints that are only temporary bootstrap seeds. "
        "Reticulum closes them after the auto-connect target is reached and restores "
        "them when no discovered boundary remains.",
        kind="endpoint-list",
        required="RNS_PUBLIC_DISCOVERY=auto or trusted_auto",
        applies_when=(("RNS_PUBLIC_DISCOVERY", ("auto", "trusted_auto")),),
    ),
    _field(
        "RNS_PRIVATE_UPSTREAMS",
        "public",
        "Private host:port boundary interfaces protected by the dedicated private-upstream IFAC.",
        kind="endpoint-list",
    ),
    _field(
        "RNS_PRIVATE_BOOTSTRAP_UPSTREAMS",
        "public",
        "Tick configured private IFAC boundary endpoints that are only temporary auto-discovery "
        "bootstrap seeds. They use the shared private-upstream IFAC profile.",
        kind="endpoint-list",
        required="RNS_PUBLIC_DISCOVERY=auto or trusted_auto",
        applies_when=(("RNS_PUBLIC_DISCOVERY", ("auto", "trusted_auto")),),
    ),
    _field(
        "RNS_PRIVATE_UPSTREAM_IFAC_NAME",
        "ifac",
        "IFAC network name shared by all configured private upstream boundaries.",
        advanced=True,
        required="RNS_PRIVATE_UPSTREAMS is not empty",
        applies_when=(("RNS_PRIVATE_UPSTREAMS", ("__nonempty__",)),),
    ),
    _field(
        "RNS_PRIVATE_UPSTREAM_IFAC_PASSPHRASE",
        "ifac",
        "Private-upstream IFAC secret; its value is never returned by Console.",
        advanced=True,
        required="RNS_PRIVATE_UPSTREAMS is not empty",
        applies_when=(("RNS_PRIVATE_UPSTREAMS", ("__nonempty__",)),),
    ),
    _field(
        "RNS_LAN_PUBLIC_VISIBILITY",
        "public",
        "Explicitly expose public announces to trusted LAN/VPN clients without exporting them to LoRa.",
        default="no",
        choices=("no", "yes"),
    ),
    _field(
        "RNS_PUBLIC_DISCOVERY",
        "discovery",
        "off disables discovery; manual observes candidates but never connects; auto mirrors "
        "Columba and connects valid discovered boundaries up to the limit; trusted_auto restricts "
        "auto-connect to explicitly trusted source identities.",
        default="off",
        choices=("off", "manual", "auto", "trusted_auto"),
    ),
    _field(
        "RNS_DISCOVERY_SOURCES",
        "discovery",
        "Comma-separated 32-hex identity hashes that are allowed to publish interface-discovery "
        "records. These are not hostnames and are not ordinary RNS destination hashes.",
        applies_when=(("RNS_PUBLIC_DISCOVERY", ("manual", "trusted_auto")),),
    ),
    _field(
        "RNS_DISCOVERY_MAX",
        "discovery",
        "Maximum concurrently auto-connected boundary interfaces. This is a capacity limit, "
        "not a latency or proximity benchmark.",
        default="1",
        kind="integer",
        minimum=1,
        maximum=8,
        applies_when=(("RNS_PUBLIC_DISCOVERY", ("auto", "trusted_auto")),),
    ),
    _field(
        "RNS_DISCOVERY_REQUIRED_VALUE",
        "discovery",
        "Minimum cryptographic stamp value accepted for discovered interfaces.",
        default="14",
        kind="integer",
        minimum=1,
        maximum=255,
        advanced=True,
        applies_when=(("RNS_PUBLIC_DISCOVERY", ("manual", "auto", "trusted_auto")),),
    ),
    _field(
        "RNS_DISCOVERY_GRAVITY",
        "discovery",
        "Reticulum gravity assigned to auto-connected interfaces; lower values are preferred.",
        default="0",
        kind="integer",
        minimum=-100,
        maximum=100,
        advanced=True,
        applies_when=(("RNS_PUBLIC_DISCOVERY", ("auto", "trusted_auto")),),
    ),
    _field(
        "RNS_RESPOND_TO_PROBES",
        "discovery",
        "Allow the Transport Instance to respond to explicit rnprobe requests.",
        default="no",
        choices=("no", "yes"),
        advanced=True,
    ),
    _field(
        "RNS_RADIO_IFAC_NAME",
        "ifac",
        "Optional IFAC network name for the radio side. Edit protected values in the env file.",
        advanced=True,
    ),
    _field(
        "RNS_RADIO_IFAC_PASSPHRASE",
        "ifac",
        "Radio IFAC secret; its value is never returned by Console.",
        advanced=True,
    ),
    _field("RNS_TCP_IFAC_NAME", "ifac", "Optional IFAC network name for trusted LAN clients.", advanced=True),
    _field(
        "RNS_TCP_IFAC_PASSPHRASE",
        "ifac",
        "LAN IFAC secret; its value is never returned by Console.",
        advanced=True,
    ),
    _field(
        "RNS_TCP_PUBLISH_IP",
        "lan",
        "Host address used to publish the Reticulum TCP listener; keep it on loopback or trusted VPN.",
        default="127.0.0.1",
    ),
    _field(
        "RNS_TCP_LISTEN_PORT",
        "lan",
        "Reticulum TCP listener port for LAN/VPN clients.",
        default="4242",
        kind="integer",
        minimum=1,
        maximum=65535,
    ),
    _field(
        "RNS_LAN_ALLOWLIST",
        "lan",
        "Optional IPv4/IPv6 address or CIDR allowlist. Empty permits every source not denied. "
        "The observed socket IP is not a Reticulum identity.",
        kind="network-list",
        advanced=True,
    ),
    _field(
        "RNS_LAN_DENYLIST",
        "lan",
        "IPv4/IPv6 addresses or CIDR networks rejected before a Reticulum client interface is created. "
        "Deny rules override allow rules and require Stage then CLI apply.",
        kind="network-list",
        advanced=True,
    ),
    _field(
        "RNS_LOGLEVEL",
        "lan",
        "Reticulum log level from 0 to 7.",
        default="4",
        kind="integer",
        minimum=0,
        maximum=7,
        advanced=True,
    ),
    _field(
        "RNS_CONSOLE_PUBLISH_IP",
        "lan",
        "Console bind published by Docker; never expose it directly to the public Internet.",
        default="127.0.0.1",
    ),
    _field(
        "RNS_CONSOLE_PORT",
        "lan",
        "Gateway Console HTTP port.",
        default="8787",
        kind="integer",
        minimum=1,
        maximum=65535,
        advanced=True,
    ),
    _field(
        "RNS_CONSOLE_AUTH_MODE",
        "lan",
        "HTTP authentication mode. Basic authentication is mandatory outside loopback and "
        "still requires VPN or HTTPS.",
        default="off",
        choices=("off", "basic"),
    ),
    _field(
        "RNS_CONSOLE_USERNAME",
        "lan",
        "Console Basic-auth username. It is not a secret, but should not identify a personal account.",
        advanced=True,
        required="RNS_CONSOLE_AUTH_MODE=basic",
        applies_when=(("RNS_CONSOLE_AUTH_MODE", ("basic",)),),
    ),
    _field(
        "RNS_CONSOLE_PASSWORD",
        "lan",
        "Console password; never returned by Console. Use at least 16 random characters and VPN or HTTPS.",
        advanced=True,
        required="RNS_CONSOLE_AUTH_MODE=basic",
        applies_when=(("RNS_CONSOLE_AUTH_MODE", ("basic",)),),
    ),
    _field(
        "LXMD_NODE_NAME",
        "lxmd",
        "Internal LXMD propagation-node name.",
        default="RNS Meshtastic Propagation",
        advanced=True,
    ),
    _field(
        "LXMD_DISPLAY_NAME",
        "lxmd",
        "Human-readable propagation-node display name.",
        default="RNS Meshtastic Service",
    ),
    _field(
        "LXMD_ANNOUNCE_INTERVAL",
        "lxmd",
        "Automatic propagation announce interval in minutes.",
        default="360",
        kind="integer",
        minimum=60,
        maximum=10080,
    ),
    _field(
        "LXMD_MANUAL_ANNOUNCE_COOLDOWN_SECONDS",
        "lxmd",
        "Minimum time between operator-triggered announces. Values below five minutes are forbidden.",
        default="900",
        kind="integer",
        minimum=300,
        maximum=86400,
        advanced=True,
    ),
    _field(
        "LXMD_AUTOPEER",
        "lxmd",
        "Automatic propagation peering. Keep disabled on shared LoRa.",
        default="no",
        choices=("no", "yes"),
        advanced=True,
    ),
    _field(
        "LXMD_FROM_STATIC_ONLY",
        "lxmd",
        "Accept propagation sync offers only from configured static peers.",
        default="yes",
        choices=("yes", "no"),
        advanced=True,
    ),
    _field(
        "LXMD_STORAGE_LIMIT_MB",
        "lxmd",
        "Maximum local propagation message store in MiB.",
        default="64",
        kind="integer",
        minimum=8,
        maximum=4096,
    ),
    _field(
        "LXMD_MESSAGE_MAX_KB",
        "lxmd",
        "Maximum accepted propagation message in KiB.",
        default="8",
        kind="integer",
        minimum=1,
        maximum=256,
        advanced=True,
    ),
    _field(
        "LXMD_SYNC_MAX_KB",
        "lxmd",
        "Maximum accepted propagation sync transfer in KiB.",
        default="64",
        kind="integer",
        minimum=8,
        maximum=10240,
        advanced=True,
    ),
    _field(
        "LXMD_AUTH_REQUIRED",
        "lxmd",
        "Require identity authentication for propagation clients.",
        default="no",
        choices=("no", "yes"),
    ),
    _field(
        "LXMD_ALLOWED_IDENTITIES",
        "lxmd",
        "Comma-separated allowed identity hashes when LXMD authentication is enabled.",
        advanced=True,
    ),
    _field(
        "LXMD_LOGLEVEL",
        "lxmd",
        "LXMD log level from 0 to 7.",
        default="4",
        kind="integer",
        minimum=0,
        maximum=7,
        advanced=True,
    ),
)


def config_schema() -> dict[str, Any]:
    names = tuple(field["name"] for field in FIELDS)
    if names != MANAGED_FIELDS:
        raise RuntimeError("configuration schema and managed environment fields are out of sync")
    return {
        "schema": 2,
        "groups": [{"id": key, "label": label} for key, label in GROUPS],
        "fields": list(FIELDS),
        "policy_profiles": {name: dict(values) for name, values in POLICY_PROFILES.items()},
    }
